/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Order = {
	_id: string;
	_type: 'order';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	orderNumber?: string;
	invoice?: {
		id?: string;
		number?: string;
		hosted_invoice_url?: string;
	};
	stripeCheckoutSessionId?: string;
	stripeCustomerId?: string;
	clerkUserId?: string;
	customerName?: string;
	email?: string;
	stripePaymentIntentId?: string;
	products?: Array<{
		product?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'product';
		};
		quantity?: number;
		_key: string;
	}>;
	totalPrice?: number;
	currency?: string;
	amountDiscount?: number;
	status?: 'pending' | 'paid' | 'shipped' | 'delivered' | 'cancelled';
	orderDate?: string;
};

export type Product = {
	_id: string;
	_type: 'product';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	slug?: Slug;
	intro?: string;
	description?: string;
	price?: number;
	discount?: number;
	stock?: number;
	category?: Array<{
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: 'category';
	}>;
	status?: 'new' | 'hot' | 'sale';
	variant?: 'tshirt' | 'jacket' | 'pants' | 'hoodie' | 'shorts' | 'other';
	images?: Array<{
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
		_key: string;
	}>;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type Category = {
	_id: string;
	_type: 'category';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	description?: string;
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| Order
	| Product
	| SanityImageCrop
	| SanityImageHotspot
	| Slug
	| Category
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/helpers/queries.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type=="product" && slug.current == $slug][0]
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
	_id: string;
	_type: 'product';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	slug?: Slug;
	intro?: string;
	description?: string;
	price?: number;
	discount?: number;
	stock?: number;
	category?: Array<{
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: 'category';
	}>;
	status?: 'hot' | 'new' | 'sale';
	variant?: 'hoodie' | 'jacket' | 'other' | 'pants' | 'shorts' | 'tshirt';
	images?: Array<{
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
		_key: string;
	}>;
} | null;

// Source: sanity/helpers/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type=="category"] | order(title asc)
export type CATEGORIES_QUERY_RESULT = Array<{
	_id: string;
	_type: 'category';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	description?: string;
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
}>;

// Source: sanity/helpers/queries.ts
// Variable: CLIENT_ORDERS_QUERY
// Query: *[_type == 'order' && clerkUserId == $userId] | order(orderData desc){		...,products[]{			...,product->		}	}
export type CLIENT_ORDERS_QUERY_RESULT = Array<{
	_id: string;
	_type: 'order';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	orderNumber?: string;
	invoice?: {
		id?: string;
		number?: string;
		hosted_invoice_url?: string;
	};
	stripeCheckoutSessionId?: string;
	stripeCustomerId?: string;
	clerkUserId?: string;
	customerName?: string;
	email?: string;
	stripePaymentIntentId?: string;
	products: Array<{
		product: {
			_id: string;
			_type: 'product';
			_createdAt: string;
			_updatedAt: string;
			_rev: string;
			name?: string;
			slug?: Slug;
			intro?: string;
			description?: string;
			price?: number;
			discount?: number;
			stock?: number;
			category?: Array<{
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				_key: string;
				[internalGroqTypeReferenceTo]?: 'category';
			}>;
			status?: 'hot' | 'new' | 'sale';
			variant?: 'hoodie' | 'jacket' | 'other' | 'pants' | 'shorts' | 'tshirt';
			images?: Array<{
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
				_key: string;
			}>;
		} | null;
		quantity?: number;
		_key: string;
	}> | null;
	totalPrice?: number;
	currency?: string;
	amountDiscount?: number;
	status?: 'cancelled' | 'delivered' | 'paid' | 'pending' | 'shipped';
	orderDate?: string;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
	interface SanityQueries {
		'*[_type=="product" && slug.current == $slug][0]': PRODUCT_BY_SLUG_QUERY_RESULT;
		'*[_type=="category"] | order(title asc)': CATEGORIES_QUERY_RESULT;
		"*[_type == 'order' && clerkUserId == $userId] | order(orderData desc){\n\t\t...,products[]{\n\t\t\t...,product->\n\t\t}\n\t}": CLIENT_ORDERS_QUERY_RESULT;
	}
}
